CREATE TABLE IF NOT EXISTS endorsements (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  name TEXT NOT NULL,
  role TEXT NOT NULL,
  rating INTEGER NOT NULL,
  message TEXT NOT NULL
);
